default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_development
  password: <%= ENV.fetch("RAILS_API_DATABASE_PASSWORD") %>
  user: karina

test:
  <<: *default
  database: rails_api_test

production:
  primary: &primary_production
    <<: *default
    database: rails_api_production
    username: rails_api
    password: <%= ENV["RAILS_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_api_production_cable
    migrations_paths: db/cable_migrate
